import * as THREE from "three";
import PropStatic from "../../entities/PropStatic";

export class NatureCollection {
    static items = ["BirchTree_1.gltf","DeadTree_3.gltf","Grass_Wispy_Short.gltf","Pine_2.gltf","BirchTree_2.gltf","DeadTree_4","Grass_Wispy_Tall.gltf","Pine_3.gltf","BirchTree_3.gltf","DeadTree_4.gltf","MapleTree_1.gltf","Pine_4.gltf","BirchTree_4.gltf","DeadTree_5","MapleTree_2.gltf","Pine_5.gltf","BirchTree_5.gltf","DeadTree_5.gltf","MapleTree_3.gltf","Plant_1.gltf","Bush.gltf","DeadTree_6.gltf","MapleTree_4.gltf","Plant_1_Big.gltf","Bush_Common.gltf","DeadTree_7.gltf","MapleTree_5.gltf","Plant_7.gltf","Bush_Common_Flowers.gltf","DeadTree_8.gltf","Mushroom_Common.gltf","Plant_7_Big.gltf","Bush_Flowers.gltf","DeadTree_9.gltf","Mushroom_Laetiporus.gltf","RockPath_Round_Small_1.gltf","Bush_Large.gltf","Fern_1.gltf","Pebble_Round_1.gltf","RockPath_Round_Small_2.gltf","Bush_Large_Flowers.gltf","Flower_1.gltf","Pebble_Round_2.gltf","RockPath_Round_Small_3.gltf","Bush_Small.gltf","Flower_1_Clump.gltf","Pebble_Round_3.gltf","RockPath_Round_Thin.gltf","Bush_Small_Flowers.gltf","Flower_2.gltf","Pebble_Round_4.gltf","RockPath_Round_Wide.gltf","Clover_1.gltf","Flower_2_Clump.gltf","Pebble_Round_5.gltf","RockPath_Square_Small_1.gltf","Clover_2.gltf","Flower_3_Clump.gltf","Pebble_Square_1.gltf","RockPath_Square_Small_2.gltf","CommonTree_1.gltf","Flower_3_Group.gltf","Pebble_Square_2.gltf","RockPath_Square_Small_3.gltf","CommonTree_2.gltf","Flower_3_Single.gltf","Pebble_Square_3.gltf","RockPath_Square_Thin.gltf","CommonTree_3.gltf","Flower_4_Clump.gltf","Pebble_Square_4.gltf","RockPath_Square_Wide.gltf","CommonTree_4.gltf","Flower_4_Group.gltf","Pebble_Square_5.gltf","Rock_Medium_1.gltf","CommonTree_5.gltf","Flower_4_Single.gltf","Pebble_Square_6.gltf","Rock_Medium_2.gltf","DeadTree_1","Flower_5_Clump.gltf","Petal_1.gltf","Rock_Medium_3.gltf","DeadTree_1.gltf","Grass_Common_Short.gltf","Petal_2.gltf","TwistedTree_1.gltf","DeadTree_10.gltf","Grass_Common_Tall.gltf","Petal_3.gltf","TwistedTree_2.gltf","DeadTree_2","Grass_Large.gltf","Petal_4.gltf","TwistedTree_3.gltf","DeadTree_2.gltf","Grass_Large_Extruded.gltf","Petal_5.gltf","TwistedTree_4.gltf","DeadTree_3","Grass_Small.gltf","Pine_1.gltf","TwistedTree_5.gltf"];

    static createItem (name, options) {
        return new PropStatic('/assets/models/nature/' + name, options)
    }
}